Re-build hg38 annotations with GDC fasta
CCBR/RENEE pull request #136
Opened 2024-06-21 18:19 UTC by kelly-sovacool

## Changes

- Rebuilt hg38 annotations with the GDC reference fasta, which includes additional sequences. These are stored in a shared location for use in other pipelines too: `/data/CCBR_Pipeliner/db/PipeDB/GDC_refs/`
- Copied files to FRCE: `/mnt/projects/CCBR-Pipelines/db/GDC_refs`

```sh
module load ccbrpipeliner

for gver in 30 34 36 38 41 45; do
    renee build \
        --sif-cache /data/CCBR_Pipeliner/SIFS \
        --ref-fa /data/CCBR_Pipeliner/db/PipeDB/GDC_refs/GRCh38.d1.vd1.fa \
        --ref-name hg38 \
        --ref-gtf /data/CCBR_Pipeliner/db/PipeDB/Indices/GTFs/hg38/gencode.v${gver}.primary_assembly.annotation.gtf \
        --gtf-ver ${gver} \
        --output /data/CCBR_Pipeliner/db/PipeDB/GDC_refs/hg38_${gver}
done
```

## Issues

- Resolves #129 

## PR Checklist

(~Strikethrough~ any points that are not applicable.)

- [x] This comment contains a description of changes with justifications, with any relevant issues linked.
- [ ] Update docs if there are any API changes.
- [ ] Update `CHANGELOG.md` with a short description of any user-facing changes and reference the PR number. Guidelines: https://keepachangelog.com/en/1.1.0/

2024-08-02 17:39 UTC, kelly-sovacool commented
Running tests.

## Submitted

```sh
RENEE_REPO=/data/CCBR_Pipeliner/Pipelines/RENEE/renee-dev-sovacool
for genome in $(ls $RENEE_REPO/config/genomes/biowulf/ | grep hg |  sed 's/.json//'); do
    $RENEE_REPO/bin/renee run \
        --input $RENEE_REPO/.tests/*.R1.fastq.gz \
        --genome $genome \
        --mode slurm \
        --output /data/$USER/renee_test_$genome \
        --sif-cache /data/CCBR_Pipeliner/SIFS \
        &> /data/$USER/renee_shell.${genome}.out
done
```


## Job status

<details>

```sh
for f in $(ls | grep renee_shell); do genome=$(echo $f |  sed 's/renee_shell\.//' | sed 's/\.out//'); jobid=$(grep master $f | sed 's/.*: //'); echo "| $genome | $jobid |  |"; done
```

</details>

| genome  | slurm id | status |
|---------|----------|--------|
| hg19_19 | 31994530 |        |
| hg19_36lift37 | 31994535 |  |
| hg38_30 | 31994547 |  |
| hg38_34 | 31994560 |  |
| hg38_36 | 31994162 |  |
| hg38_38 | 31994566 |  |
| hg38_41 | 31994570 |  |
| hg38_45 | 31994583 |  |

2024-08-02 18:45 UTC, kopardev commented on config/genomes/biowulf/hg19_36lift37.json
For simplicity, rename the file to `hg19_36.json`

2024-08-02 18:48 UTC, kopardev commented on config/genomes/igenomes/hg19_19.json
what are these files in under `igenomes`??

2024-08-02 18:50 UTC, kopardev requested changes
Please see comments before merging.

2024-08-13 21:59 UTC, kelly-sovacool commented
@kopardev this is ready for your re-review

2024-08-27 19:09 UTC, kopardev approved these changes

2024-08-27 19:29 UTC, merged